<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Test</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="navbar-nav navbar-right nav">

                <?php if (Register::getUserId()):?>
                     <li><a href="/logout">Logout (<?=Register::getUserName()?>)</a></li>
                <?php endif;?>
                <?php if (!Register::getUserId()):?>
                    <li class="active"><a href="/register">Register</a></li>
                    <li><a href="/login">Login</a></li>
                <?php endif;?>

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <?php echo $this->content(); ?>
</div>
</body>

<script src="js/jquery-3.1.1.min.js" language="JavaScript"></script>
<script src="js/bootstrap.min.js" language="JavaScript"></script>
<script src="js/main.js" language="JavaScript"></script>
</html>